backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /uploads
locale: 'en'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:

  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "site/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: title.en
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "object"
        fields: 
        - {label: "Title En", name: "en", widget: "string"}
        - {label: "Title De", name: "de", widget: "string"}
        - {label: "Title Hu", name: "hu", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime", default: "", format: "YYYY-MM-DD HH:mm", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm" }
      - label: "Featured Image"
        name: "image"
        widget: "object"
        fields:
        - {label: "Image", name: "src", widget: "image"}
        - {label: "Caption", name: "caption", widget: "string"}
      - label: "Content"
        name: "content"
        widget: "object"
        fields:
        - {label: "Content En", name: "en", widget: "markdown"}
        - {label: "Content De", name: "de", widget: "markdown"}
        - {label: "Content Hu", name: "hu", widget: "markdown"}
      - {label: "Publish Date", name: "pub_date", widget: "datetime", format: "YYYY-MM-DD HH:mm", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm" }

  - label: "Pages"
    name: "pages"
    files:

      - label: "Landing Page"
        name: "landing"
        file: "site/pages/landing.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "object"
            fields: 
            - {label: "Title En", name: "en", widget: "string"}
            - {label: "Title De", name: "de", widget: "string"}
            - {label: "Title Hu", name: "hu", widget: "string"}
          - label: "Content"
            name: "content"
            widget: "object"
            fields:
            - {label: "Content En", name: "en", widget: "markdown"}
            - {label: "Content De", name: "de", widget: "markdown"}
            - {label: "Content Hu", name: "hu", widget: "markdown"}
          - {label: "Body", name: "body", widget: "code", default_language: "svelte"}

      - label: "About Page"
        name: "about"
        file: "site/pages/about.md"
        fields:
          - label: "Introduction"
            name: "intro"
            widget: "object"
            fields:
            - {label: "Intro En", name: "en", widget: "markdown"}
            - {label: "Intro De", name: "de", widget: "markdown"}
            - {label: "Intro Hu", name: "hu", widget: "markdown"}
          - label: CV
            name: cv
            widget: list
            fields:
              - {label: "Date", name: "date", widget: "datetime", default: "", format: "YYYY", dateFormat: "YYYY", timeFormat: false }
              - {label: Position, name: position, widget: string}
              - {label: Location, name: location, widget: string}
              - label: "Image"
                name: "image"
                widget: "object"
                fields:
                - {label: "Image", name: "src", widget: "image"}
                - label: "Caption"
                  name: "caption"
                  widget: "object"
                  fields:
                  - {label: "Caption En", name: "en", widget: "string"}
                  - {label: "Caption De", name: "de", widget: "string"}
                  - {label: "Caption Hu", name: "hu", widget: "string"}

      - label: "Photos"
        name: "photos"
        file: "site/pages/photos.md"
        fields:
          - label: Photos
            name: photos
            widget: list
            fields:
              - {label: Photo, name: photo, widget: image}
              - {label: Caption, name: caption, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: "Date", name: "date", widget: "datetime", default: "", format: "YYYY", dateFormat: "YYYY", timeFormat: false }
