title:
  en: Welcome
  de: Willkommen
  hu: Köszöntő
content:
  en: >-
    > *"Only the song through the land hallows and heals."*

    >

    > Rainer Maria Rilke: Sonnets To Orpheus – The XIXth Sonnet


    # Welcome to my website!


    It is not meant to tell about my life but to share the fascination what music has always brought to me.


    My parents often mentioned that I was not yet able to utter sounds to form comprehensible words when I cradled myself by singing already quite clearly Bach D-minor piano concerto.


    I still feel that while words may betray, sounds of music always provide me with comfort and happiness.


    Since I am not only composing music but also interpreting it as a conductor, my pleasure is in full fruition – as a kind of medium I can acquaint my audience with the music what "hallows and heals".


    With kind regards\

    \

    *Zsolt Hamar*
  hu: >-
    > *”Vannak a léleknek régiói, melyekbe csak a zene világít be.”*

    >

    > Kodály Zoltán


    # Köszöntöm a honlapomon!


    Ezen az oldalon azt a lenyűgöző varázslatot szeretném megosztani, ahogyan a zene egész életemet gazdaggá tette.


    A szüleim gyakran emlegették, hogy egy-két évesen, mielőtt még értelmes szavakat mondtam volna, már Bach D-moll zongoraversenyét tisztán dúdolgatva ringattam magam.


    Még most is gyakran úgy érzem, hogy ha a szavak időnként cserben is hagynak, a zene mindig elégedettséggel és boldogsággal tölt. el.


    Mióta nem csak komponálok, hanem karmesterként interpretálom is a zenét, örömöm teljes, mivel egyfajta közvetítőként segíthetek a közönségemnek megtapasztalni a zene felemelő és gyógyító erejét.


    Őszinte barátsággal:


    *Hamar Zsolt*
  de: >-
    > *„Einzig das Lied überm Land heiligt und feiert.“*

    >

    > Erich Maria Rilke: Sonette an Orpheus – Das XIX. Sonett


    # Ich begrüße Sie auf meiner Homepage!


    Ich habe nicht die Absicht, hier von meinem Leben zu sprechen, sondern mit Ihnen die Schönheit zu teilen, die die Musik für mich immer schon bedeutet hat.


    Meine Eltern haben oft erwähnt, dass ich noch nicht sprechen konnte, als ich mich schon mit Bachs d-moll Konzert in den Schlaf gesungen habe.


    Noch immer fühle ich, dass wenn die Worte mich manchmal im Stich lassen, die Töne der Musik mir immer Sicherheit geben und mich mit Freude erfüllen.


    Seit ich nicht nur komponiere, sondern auch als Dirigent interpretiere, ist mein Glück komplett – wie ein Vermittler konnte ich mein Gehör mit der Musik bekannt machen, welche „heiligt und feiert“.


    Mit herzlichen Grüßen


    *Zsolt Hamar*